import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/tjp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const www=path.join(root,'www');
const types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{
  try {
    const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
    const target=path.resolve(www,'.'+(pathname==='/'?'/index.html':pathname));
    if(!target.startsWith(www+path.sep))throw new Error('outside');
    res.setHeader('Content-Type',types[path.extname(target)]??'application/octet-stream');res.end(await readFile(target));
  }catch{res.writeHead(404);res.end();}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const address=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,channel:'chrome'});
try{
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
 const page=await context.newPage();const errors=[];
 page.on('pageerror',error=>{errors.push(error.message);console.error('PAGE ERROR',error.message);});
 // Deterministic tests never scrape map/photo providers or spend a user's API credits.
 await page.route('https://tile.openstreetmap.org/**',route=>route.abort());
 await page.goto(address);await page.waitForFunction(()=>document.querySelector('#manual-button')?.onclick != null);
 assert.equal(await page.locator('.mobile-tabbar [data-tab]').count(),4,'four navigation tabs');
 assert.equal(await page.locator('#mobile-pane-map').isVisible(),true);
 for(const tab of ['add','history','settings'])assert.equal(await page.locator(`#mobile-pane-${tab}`).isVisible(),false,'home only shows map');
 await page.locator('[data-tab="add"]').click();
 await page.locator('#manual-button').click();
 await page.waitForSelector('#review-dialog[open]');
 const data={code:'CA1831',date:'2026-09-01',departure:'北京首都国际机场（PEK）',arrival:'上海虹桥国际机场（SHA）',departureTime:'07:00',aircraftType:'737-8SL',registration:''};
 assert.equal(await page.locator('#review-forms input:visible').count(),2,'new flight shows only code and date');
 assert.equal(await page.locator('.review-optional').getAttribute('open'),null,'optional fields are collapsed');
 assert.equal(await page.locator('.review-minimal-note').count(),0,'no extra instructions below fields');
 assert.equal(await page.locator('#review-warnings').textContent(),'','no manual-mode instructions');
 const alerts=[];
 page.on('dialog',async dialog=>{alerts.push(dialog.message());await dialog.accept();});
 await page.locator('#review-forms [name="date"]').fill('');
 await page.locator('#save-button').click();
 assert.deepEqual(alerts,['请填写航班号和日期。']);
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('xingji:trips.json')??'[]').length),0,'incomplete draft is not saved');
 await page.locator('#review-forms [name="code"]').fill(data.code);
 await page.locator('#save-button').click();
 assert.equal(alerts.at(-1),'请填写日期。');
 await page.locator('#review-forms [name="code"]').fill('');
 await page.locator('#review-forms [name="date"]').fill(data.date);
 await page.locator('#save-button').click();
 assert.equal(alerts.at(-1),'请填写航班号。');
 for(const name of ['code','date'])await page.locator(`#review-forms [name="${name}"]`).fill(data[name]);
 await mkdir(path.join(root,'verification'),{recursive:true});
 await page.screenshot({path:path.join(root,'verification','minimal-add-phone.png')});
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('xingji:trips.json')??'[]').length),0,'draft is not stored');
 await page.locator('#save-button').click();await page.waitForSelector('#review-dialog:not([open])',{state:'attached'});
 await page.waitForFunction(()=>document.querySelector('#trip-count')?.textContent==='1');
 assert.equal(alerts.length,3,'complete minimal draft saves without any extra reminder');
 await page.locator('#toast').waitFor({state:'visible'});
 async function assertToastAboveNavigation(label){
   const layout=await page.evaluate(()=>{
     const toast=document.querySelector('#toast'),nav=document.querySelector('.mobile-tabbar');
     const t=toast.getBoundingClientRect(),n=nav.getBoundingClientRect();
     return {bottom:t.bottom,top:t.top,left:t.left,right:t.right,navTop:n.top,width:innerWidth,
       toastZ:Number(getComputedStyle(toast).zIndex),navZ:Number(getComputedStyle(nav).zIndex)};
   });
   assert.ok(layout.bottom<=layout.navTop-10,`${label}: toast clears bottom navigation`);
   assert.ok(layout.top>=0&&layout.left>=0&&layout.right<=layout.width,`${label}: toast stays on screen`);
   assert.ok(layout.toastZ>layout.navZ,`${label}: toast is not behind navigation`);
 }
 await assertToastAboveNavigation('portrait');
 await page.screenshot({path:path.join(root,'verification','toast-phone.png')});
 await page.setViewportSize({width:844,height:390});
 await assertToastAboveNavigation('landscape');
 await page.evaluate(()=>document.documentElement.style.setProperty('--mobile-bottom-inset','24px'));
 await assertToastAboveNavigation('landscape with system inset');
 await page.setViewportSize({width:390,height:844});
 await assertToastAboveNavigation('portrait with system inset');
 await page.evaluate(()=>document.documentElement.style.removeProperty('--mobile-bottom-inset'));
 await page.reload();await page.waitForFunction(()=>document.querySelector('#trip-count')?.textContent==='1');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('xingji:trips.json'))[0].departure),'','airport can remain empty');
 await page.locator('[data-tab="add"]').click();await page.locator('#manual-button').click();
 for(const name of ['code','date'])await page.locator(`#review-forms [name="${name}"]`).fill(data[name]);
 assert.equal(await page.locator('#save-button').isDisabled(),true,'minimal record still has code plus date deduplication');
 await page.locator('#cancel-review').click();
 await page.locator('[data-tab="history"]').click();
 await page.waitForFunction(()=>document.querySelector('#stats-summary')?.textContent.includes('1'));
 assert.equal(await page.locator('#route-ranking li').count(),0,'unknown airports do not become a fictional route');
 await page.locator('[data-history-view="list"]').click();
 await page.locator('#trip-list').getByRole('button',{name:'修改',exact:true}).click();
 await page.locator('.review-optional>summary').click();
 for(const [name,value] of Object.entries(data))await page.locator(`#review-forms [name="${name}"]`).fill(value);
 await page.locator('#save-button').click();await page.waitForSelector('#review-dialog:not([open])',{state:'attached'});
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('xingji:trips.json'))[0].departure.length>0);
 await page.locator('[data-tab="settings"]').click();
 assert.equal(await page.locator('#mobile-pane-settings #export-button').count(),1);
 assert.equal(await page.locator('#mobile-pane-settings #import-backup-button').count(),1);
 await page.locator('#settings-button').click();await page.locator('#api-endpoint').fill('https://vision.test/v1');
 await page.locator('#api-model').fill('vision-test');await page.locator('#api-key').fill('test-only-not-a-real-key');
 await page.locator('#settings-form button[type="submit"]').click();
 await page.waitForSelector('#settings-dialog:not([open])',{state:'attached'});
 await page.route('https://vision.test/**',route=>route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({choices:[{message:{content:JSON.stringify({trips:[{...data,type:'flight'}],warnings:[]})}}]})}));
 await page.locator('[data-tab="add"]').click();
 await page.locator('#source-text').fill('2026年9月1日 CA1831 北京首都到上海虹桥');
 await page.locator('#recognize-button').click();await page.waitForSelector('#review-dialog[open]');
 assert.equal(await page.locator('.review-optional').evaluate(el=>el.open),true,'recognized details stay visible for confirmation');
 await page.waitForFunction(()=>document.querySelector('#save-button')?.disabled===true);
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('xingji:trips.json')).length),1,'duplicate is not stored');
 await page.locator('#cancel-review').click();
 await page.goto(address+'/stats.html');await page.waitForFunction(()=>document.querySelector('#stats-summary')?.textContent.includes('1'));
 assert.ok(await page.locator('#route-ranking li').count());assert.ok(await page.locator('#airline-ranking li').count());assert.ok(await page.locator('#aircraft-ranking').textContent().then(t=>t.includes('737-800')));
 assert.equal(await page.locator('#mobile-pane-history').isVisible(),true,'legacy stats URL opens history tab');
 assert.equal(await page.locator('#mobile-pane-history .itinerary-panel').isVisible(),false,'stats and trip list are separate views');
 await page.locator('[data-history-view="list"]').click();
 assert.equal(await page.locator('#trip-list .trip-card').count(),1);
 assert.equal(await page.locator('#trip-list').isVisible(),true);
 await page.locator('[data-history-view="stats"]').click();
 const initialTrips=await page.evaluate(()=>JSON.parse(localStorage.getItem('xingji:trips.json')));
 await page.evaluate(({original})=>{
   const carriers=['CA','MU','CZ','SC','ZH','HO','9C','HU','GS','PN','KN','MF'];
   const types=['A320','A321','737 MAX 8','A350-900','A330-300','787-9'];
   const extra=carriers.map((carrier,index)=>({type:'flight',id:`ranking-${index}`,code:`${carrier}${1000+index}`,date:'2026-01-01',departure:`测试出发 ${index}`,arrival:`测试到达 ${index}`,aircraftType:types[index%types.length]}));
   localStorage.setItem('xingji:trips.json',JSON.stringify([...original,...extra]));
 },{original:initialTrips});
 await page.reload();await page.waitForFunction(()=>document.querySelector('#stats-summary')?.textContent.includes('13'));
 assert.equal(await page.locator('#route-ranking li').count(),10,'route ranking is top 10');
 assert.equal(await page.locator('#airline-ranking li').count(),12,'all airlines are shown');
 assert.equal(await page.locator('#aircraft-ranking li').count(),7,'all base aircraft models are shown');
 await page.evaluate(original=>localStorage.setItem('xingji:trips.json',JSON.stringify(original)),initialTrips);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#stats-summary')?.textContent.includes('1'));
 await mkdir(path.join(root,'verification'),{recursive:true});await page.screenshot({path:path.join(root,'verification','stats-phone.png'),fullPage:true});
 await page.goto(address);await page.waitForFunction(()=>document.querySelector('#trip-count')?.textContent==='1');
 await page.locator('[data-tab="map"]').click();
 await page.waitForFunction(()=>document.querySelector('.leaflet-container')?.clientWidth>0);
 await page.waitForSelector('#map-canvas[data-offline-basemap="ready"]');
 await page.waitForFunction(()=>document.querySelector('#map-count')?.textContent==='1 条航线');
 assert.equal(await page.locator('.map-node-icon').count(),2,'airport markers survive global map upgrade');
 assert.equal(await page.locator('.map-foot').isVisible(),false,'resolved trips do not show removed footer text');
 await page.screenshot({path:path.join(root,'verification','home-phone.png'),fullPage:true});
 assert.deepEqual(errors,[],'no page runtime errors');
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,'no horizontal overflow');
 await page.setViewportSize({width:844,height:390});
 await page.waitForTimeout(150);
 assert.equal(await page.locator('.mobile-tabbar').isVisible(),true,'landscape retains bottom navigation');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'landscape has no horizontal overflow');
 const report={passed:true,checks:['地图为唯一首页卡片','四栏导航','提示在导航上方（横竖屏与系统安全区）','设置集中API和备份入口','确认前不保存','新增与刷新后保留','自定义 API 配置','AI 识别与重复阻止','历史统计/具体行程切换','旧统计地址兼容','统计三榜单','737 细分型归并','地图切回恢复尺寸','页面无运行错误','手机无横向溢出']};
 await writeFile(path.join(root,'verification','browser-smoke.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
